url: "https://jmillanacosta.github.io"
baseurl: ""
canonical: "https://jmillanacosta.github.io/"
title: "Javier Millán Acosta"
exclude:
  - vendor
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - tmp
  - node_modules
  - package.json
  - package-lock.json
plugins:
  - jekyll-seo-tag
